name: GitHub Pages

on:
  push:
    branches: [ "web" ]  # 触发分支改为 "web"
  pull_request:
    branches: [ "web" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: web  # 检出 web 分支
        submodules: recursive

    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: .
        destination: ./_site

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
